twitter clone/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^twitter/', include('twitter.urls', namespace='twitter'))
]

twitter clone/twitter/urls.py
from django.conf.urls import url
from twitter import views


urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
]

twitter clone/users/urls.py
from django.conf.urls import url
from users import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create$', views.CreateUserView.as_view(), name='create'),
	url(r'^login$', views.UserLoginView.as_view(), name='login'),
]

twitter clone/twitter/models.py
from django.db import models

# Create your models here.

twitter clone/users/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=20)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

twitter clone/users/forms.py
from django import forms
from django.core.exceptions import ValidationError


from users.models import User

class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']
    
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput())
    
    
    
    
    def clean(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise ValidationError('Passwords must match')
        
        else:
            self.cleaned_data['password'] = self.cleaned_data['password1']
            self.cleaned_data.pop('password1')
            self.cleaned_data.pop('password2')
            
        return self.cleaned_data


class UserLoginForm(forms.Form):
    
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())

twitter clone/twitter/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
User = get_user_model()


def get_user(request):
	return User.objects.get(id=request.session['user_id'])

class IndexView(LoginRequiredMixin, View):

	def get(self, request):

		return render(request, 'twitter/index.html')

twitter clone/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.conf import settings
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


from users.forms import UserLoginForm

User = get_user_model()
# Create your views here.
def logout_view(request):
    logout(request)

    return redirect("users:index")

class IndexView(View):
	
	def get(self, request):
		return render(request, 'users/index.html')
		

class CreateUserView(View):
	form_class = UserCreationForm
	
	def get(self, request):
		context = {
			'user_creation_form': self.form_class()
		}
		return render(request, 'users/create.html', context)
		
		
	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			#User.objects.create(**form.cleaned_data)
			user = form.save()
			login(request, user)
			return redirect(settings.LOGIN_SUCCESS_PAGE)
		else:
			context = {
				'user_creation_form': form
			}
			return render(request, 'users/create.html', context)

class UserLoginView(View):

    form_class = AuthenticationForm

    def get(self, request):
        context = {
            'user_login_form': self.form_class()
        }
        return render(request, 'users/login.html', context)
        
        
    def post(self, request):
        form = self.form_class(request=request, data=request.POST)
        error = "YA DUN GOOFED. CONTACTING THE CYBER POLICE."
        

        if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, user)
                return redirect(settings.LOGIN_SUCCESS_PAGE)
        context = {
            'user_login_form': form
        }
        return render(request, 'users/login.html', context)

twitter clone/twitter/templates/twitter/_base.html
<!DOCTYPE html>
<html>
    <head>
     <title>
         {% block title %} {% endblock title %}
     </title>   
    </head>  
    <body>
       {% block header %} {% endblock header %}
       {% block main %} {% endblock main %}
       {% block footer %} {% endblock footer %}
    </body> 
</html>

twitter clone/twitter/templates/twitter/index.html
{% extends 'twitter/_base.html' %}
{% load staticfiles %}

{% block title %}Weclome to Twitter!{% endblock title %}

{% block header %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static '/twitter/js/main.js' %}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Mukta" rel="stylesheet">
<link rel="stylesheet" href="{% static '/twitter/css/style.css' %}">

{% endblock header %}

{% block main %}
<a href="/users">Log out</a>
<div>
    <h1>Welcome to Twitter</h1> 
</div>

<div>
	{% if user.is_authenticated %}
	<h2>Weclome back, @{{ user.get_username }}!</h2>
	{% endif %}
</div>
<div>
	<p hidden id="user">{{ user.get_username }}</p>
</div>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-8">
			<form id="create-tweet">
				<h3>Create a Tweet!</h3><br>
				<input type="text" name="tweet" placeholder="Place your tweet here" id="textinput">
				<input type="submit" class="btn btn-success" name="submit" value="submit">
				<input type="hidden" value="{{ user.get_username }}" id="created_by">
			</form>
		</div>
	</div>
</div>

<div class="container">
	<div id="tweetlist" class="row justify-content-center">

	</div>
</div>

{% endblock main %}

{% block footer %} {% endblock footer %}

twitter clone/users/templates/users/_base.html
<!DOCTYPE html>
<html>
    <head>
     <title>
         {% block title %} {% endblock title %}
     </title>   
    </head>  
    <body>
       {% block header %} {% endblock header %}
       {% block main %} {% endblock main %}
       {% block footer %} {% endblock footer %}
    </body> 
</html>

twitter clone/users/templates/users/create.html
{% extends 'users/_base.html' %}

{% block title %}Create user {% endblock title %}

{% block header %} {% endblock header %}

{% block main %}
<div>
    <form action="{% url 'users:create' %}" method="POST">
         {{user_creation_form}}  
         {% csrf_token %}
        <input type="submit" value="Submit"/>
    </form>
</div>
{% endblock main %}

{% block footer %} {% endblock footer %}

twitter clone/users/templates/users/index.html
{% extends 'users/_base.html' %}

{% block title %}Weclome to Twitter!{% endblock title %}

{% block header %} {% endblock header %}

{% block main %}
<div>
    <p>
        <a href="{% url 'users:create' %}"> Register 
        </a>
    </p>
    <p>
        <a href="{% url 'users:login' %}"> Login 
        </a>
    </p> 
</div>
{% endblock main %}

{% block footer %} {% endblock footer %}

twitter clone/users/templates/users/login.html
{% extends 'users/_base.html' %}

{% block title %}Login Page {% endblock title %}

{% block header %} 
	<a href="{% url 'users:create' %}"> Register </a>
{% endblock header %}

{% block main %}
<div>
    <form action="{% url 'users:login' %}" method="POST">
         {{user_login_form}}  
         {% csrf_token %}
        <input type="submit" value="Login"/>
    </form>
</div>
{% endblock main %}

{% block footer %} {% endblock footer %}